name: pruebas hola mundo docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 Login docker GitHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Paso 3 - configurar la imagen docker
        run: docker build -t contenedor .
      - name: Paso 4 - Ejecutar extractor
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/workspaces/PAD_2025_1/src/edu_pad/static/csv \
            -v "${{ github.workspace }}/workspaces/PAD_2025_1/src/edu_pad/static/db \
            contenedor edu_pad.main_extractor

      - name: Paso 5 - Ejecutar ingesta
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/workspaces/PAD_2025_1/src/edu_pad/static/csv\
            -v "${{ github.workspace }}/workspaces/PAD_2025_1/src/edu_pad/static/db \
            contenedor edu_pad.main_ingesta 
